### ISSUE TITLE
please start making interesting project

### ISSUE THREAD

**Issue by MateoViota** [Rinnegatamante/vitaGL#1]
like 3d engine for ps vita game engine for vita stop doin quake shit plz dude :(

**Comment by SHROOMKINGonDMT** [comment]
you DO realize that it's extremely rude to tell someone to stop working on their own projects just because you don't care about it?

he is doing all this for free and you need to learn to appreciate the fact. programming is not easy and takes up a lot of time but you don't seem to know about that.

if you want him to do something you should ask him nicely, and he might do it if he's interested in whatever you want from him. this way you'll just be ignored.

vitaQuake are great projects, just ignore this troll rinne.  i appreciate all your work and look forward to make some stuff with GL. thanks again for ALL the time you put into the vita scene!

**Comment by MateoViota** [comment]
shut up sjw
