### ISSUE TITLE
OpenGL Additions 

### ISSUE THREAD

**Issue by Corbachu** [Rinnegatamante/vitaGL#31]
Hi @Rinnegatamante , very cool work you've been doing in regards to the Vita scene as a whole. =)

Just getting into Vita development, as I'm on a quest to port my engine [EDGE](https://github.com/3dfxdev/EDGE) to Vita. EDGE is an enhanced, GPL-licensed, OpenGL only port of id Tech 1; think of it as an in-between of GZDoom and Eternity.

So - you having developed a wrapper for OpenGL - I decided to take my hand and begin a slow port to the Vita, which is one of my favorite platforms. 

However I do have some requests for some older and newer implementations of GL into vitaGL:

> The below functions are older OpenGL. In the case of GL_POLYGON, I suppose I can swap that code to just use GL_TRIANGLE_FAN, but just throwing it out there:

```
GL_LINE_SMOOTH
GL_POLYGON
```

> The next two are OpenGL2. I know you have the float variations implemented:

```
glVertex2i
glVertex3i
```

> The below functions are used for swapping buffers in regards to Post-Processing shaders (newer GL functions), primarily used for Camera Exposure, Blooming the scene, and lens distortion. These are used [here](https://github.com/3dfxdev/EDGE/blob/master/src/r_shaderprogram.h) and [here](https://github.com/3dfxdev/EDGE/blob/20059cb6fc78bd19471e7b1c73b20b043a9d2c52/src/hu_draw.cc#L665).

```
glUniform1i
glUniform4iv
glUniform4f

GL_DRAW_FRAMEBUFFER
GL_READ_FRAMEBUFFER
glBindFramebuffer
glBlitFramebuffer
```

Thank you for your hard work again! I look forward to your response and/or any help I can get.

**Comment by Rinnegatamante** [comment]
GL_POLYGON as you said can be replaced with GL_TRIANGLE_FAN.
glVertex functions should be avoided if possible and instead vitaGL unique ones should be used. (or at least the GL ES ones).

Uniforms functions can be added.
As for Framebuffers, they're not that easy to implement. That's why they're not yet in vitaGL as of now.

Since you said EDGE is an id Tech 1 GL port, take a look at my vitaQuake: https://github.com/Rinnegatamante/vitaQuake

This is a source port of id Tech 2 using vitaGL. Maybe it will help (all original drawing functions had been replaced with vitaGL unique ones that offer better performances cause take advantage of how sceGxm works).

For any further questions, please join Henkaku discord server for a faster comunication: https://discord.gg/m7MwpKA

**Comment by Rinnegatamante** [comment]
Update on this:
As of today:
- glUniform funcs are all implemented
- FBOs are implemented as well (so glBindFramebuffer is)
- glVertex funcs are also implemented although I HIGLY suggest to not use immediate mode.
- GL_POLYGON has been implemented as well.

Of the requests here, what's missing are:
- GL_LINE_SMOOTH
- glBlitFramebuffer

**Comment by Rinnegatamante** [comment]
glBlitFramebuffer is now also available making only GL_LINE_SMOOTH not usable although it can be easily replicated by just having MSAA enabled in vitaGL.
Closing this issue.
